const { contextBridge, ipcRenderer } = require('electron');

function on(channel, callback) {
  const wrapped = (_, payload) => callback(payload);
  ipcRenderer.on(channel, wrapped);
  return () => ipcRenderer.removeListener(channel, wrapped);
}

contextBridge.exposeInMainWorld('antbot', {
  getInitialState: () => ipcRenderer.invoke('app:get-initial-state'),
  checkStartup: () => ipcRenderer.invoke('startup:check'),
  markLoginDone: (serviceKey) => ipcRenderer.invoke('startup:mark-login-done', serviceKey),
  openLoginWindow: (serviceKey) => ipcRenderer.invoke('startup:open-login-window', serviceKey),
  updateSettings: (settings) => ipcRenderer.invoke('settings:update', settings),
  listGeminiProfiles: () => ipcRenderer.invoke('gemini-profiles:list'),
  createGeminiProfile: (name) => ipcRenderer.invoke('gemini-profiles:create', name),
  pickAudioFile: () => ipcRenderer.invoke('dialog:pick-audio-file'),
  pickVideoFile: () => ipcRenderer.invoke('dialog:pick-video-file'),
  pickVideoFiles: () => ipcRenderer.invoke('dialog:pick-video-files'),
  runVoiceClone: (payload) => ipcRenderer.invoke('voice:clone', payload),
  parseTasks: (input) => ipcRenderer.invoke('task:parse', input),
  startTasks: (input) => ipcRenderer.invoke('task:start', input),
  stopTasks: () => ipcRenderer.invoke('task:stop'),
  stopTask: (taskId) => ipcRenderer.invoke('task:stop-one', taskId),
  resumeTask: (payload) => ipcRenderer.invoke('task:resume-one', payload),
  getHistory: () => ipcRenderer.invoke('history:get'),
  getDependencyState: () => ipcRenderer.invoke('deps:get-state'),
  repairDependencies: () => ipcRenderer.invoke('deps:repair'),
  openExternal: (url) => ipcRenderer.invoke('app:open-external', url),
  openDataDir: () => ipcRenderer.invoke('app:open-data-dir'),
  openDepDir: (toolKey) => ipcRenderer.invoke('deps:open-dir', toolKey),
  uninstallDep: (toolKey) => ipcRenderer.invoke('deps:uninstall', toolKey),
  reinstallDep: (toolKey) => ipcRenderer.invoke('deps:reinstall', toolKey),
  checkDep: (tool) => ipcRenderer.invoke('deps:check', tool),
  installDep: (tool) => ipcRenderer.invoke('deps:install', tool),
  voiceboxCheck: () => ipcRenderer.invoke('voicebox:check'),
  voiceboxInstall: () => ipcRenderer.invoke('voicebox:install'),
  voiceboxOpenDir: () => ipcRenderer.invoke('voicebox:open-dir'),
  voiceboxReset: () => ipcRenderer.invoke('voicebox:reset'),
  getDataInfo: () => ipcRenderer.invoke('app:get-data-info'),
  migrateData: () => ipcRenderer.invoke('app:migrate-data'),
  appLog: (level, message) => ipcRenderer.invoke('app:log', { level, message }),
  fetchModels: (params) => ipcRenderer.invoke('api:fetch-models', params),
  apiTranscribe: (params) => ipcRenderer.invoke('api:transcribe', params),
  styleLearnFromVideo: (params) => ipcRenderer.invoke('style:learn-from-video', params),
  listFonts: () => ipcRenderer.invoke('fonts:list'),
  addFont: (params) => ipcRenderer.invoke('fonts:add', params),
  removeFont: (name) => ipcRenderer.invoke('fonts:remove', name),
  setActiveFont: (name) => ipcRenderer.invoke('fonts:set-active', name),
  pickFontFile: () => ipcRenderer.invoke('fonts:pick-file'),
  loadStyles: () => ipcRenderer.invoke('styles:load'),
  saveStyles: (styles) => ipcRenderer.invoke('styles:save', styles),
  deleteStyle: (styleId) => ipcRenderer.invoke('styles:delete', styleId),
  saveOneStyle: (style) => ipcRenderer.invoke('styles:save-one', style),
  listVoices: () => ipcRenderer.invoke('voices:list'),
  saveVoices: (voices) => ipcRenderer.invoke('voices:save', voices),
  loadUISettings: () => ipcRenderer.invoke('ui:load'),
  saveUISettings: (ui) => ipcRenderer.invoke('ui:save', ui),
  modelsList: () => ipcRenderer.invoke('models:list'),
  modelsDownload: (modelKey) => ipcRenderer.invoke('models:download', modelKey),
  modelsDelete: (modelKey) => ipcRenderer.invoke('models:delete', modelKey),
  modelsOpenDir: () => ipcRenderer.invoke('models:open-dir'),
  modelsChangePath: (newPath) => ipcRenderer.invoke('models:change-path', newPath),
  onProgress: (callback) => on('task:progress', callback),
  onModelsProgress: (callback) => on('models:progress', callback),
  onLog: (callback) => on('task:log', callback),
  onVoiceCloneProgress: (callback) => on('voice:clone-progress', callback),
  onStartupStatus: (callback) => on('startup:status', callback),
  onHistoryChanged: (callback) => on('history:changed', callback),
  onAppState: (callback) => on('app:state', callback),
  onDepProgress: (callback) => on('deps:progress', callback),
  onDepInstallProgress: (callback) => on('deps:install-progress', callback),
  onVoiceboxProgress: (callback) => on('voicebox:progress', callback),
  onStyleProgress: (callback) => on('style:progress', callback),
});
